//!
//! # Example of use :
//! ```no_run
//!use serde::{Serialize, Deserialize};
//!use actix_restful::{
//!     HttpCreate,
//!     HttpFindListDelete,
//!     HttpUpdate,
//!     Model,
//!     NewModel,
//!     UpdatableModel,
//!     actix_restful_info,
//!     anyhow::Result,
//!     async_trait,
//!     gen_endpoint,
//!};
//!use chrono::prelude::*;
//!
//!struct AppState {}
//!#[derive(Default, Deserialize)]
//!struct FindQuery {}
//!#[derive(Deserialize)]
//!struct ListQuery {}
//!#[derive(Deserialize)]
//!struct DeleteQuery {}
//!type ListResult = Vec<Item>;
//!type DeleteResult = Item;
//!#[derive(Deserialize)]
//!struct SaveQuery {}
//!#[derive(Deserialize)]
//!struct UpdateQuery {}
//!type Id = i64;
//!
//!#[derive(Default, Serialize, Deserialize, HttpFindListDelete)]
//!#[http_find_list_delete(Id, FindQuery, ListQuery, DeleteQuery, AppState)]
//!#[actix_restful_info(path = "item")]
//!struct Item {
//!    id: Id,
//!    content: String,
//!    deleted_at: Option<DateTime<Utc>>,
//!    updated_at: Option<DateTime<Utc>>,
//!    created_at: Option<DateTime<Utc>>,
//!}
//!
//!#[async_trait]
//!impl Model<Id, FindQuery, ListQuery, ListResult, DeleteQuery, DeleteResult, AppState> for Item {
//!    async fn find(id: Id, _query: &FindQuery, _state: &AppState) -> Result<Box<Item>> {
//!        // fetch from somwhere with id and return result
//!        Ok(
//!            Box::new(
//!                Item {
//!                    id,
//!                    content: String::from("test"),
//!                    deleted_at: None,
//!                    updated_at: None,
//!                    created_at: None,
//!                }
//!            )
//!        )
//!    }
//!    async fn list(_query: &ListQuery, _state: &AppState) -> Result<ListResult> {
//!        // list
//!        let mut res = Vec::new();
//!        for i in 0..2{
//!            res.push(Item {
//!                id: i,
//!                content: String::from("test"),
//!                deleted_at: None,
//!                updated_at: None,
//!                created_at: None,
//!            });
//!        }
//!        Ok(res)
//!    }
//!    async fn delete(mut self: Self, _query: &DeleteQuery, _state: &AppState) -> Result<DeleteResult> {
//!        // hard or soft delete
//!        let utc: DateTime<Utc> = Utc::now();
//!        self.deleted_at = Some(utc);
//!        Ok(self)
//!    }
//!}
//!
//!#[derive(Serialize, Deserialize, HttpCreate)]
//!#[http_create(SaveQuery, AppState)]
//!struct NewItem {
//!     content: String,
//!}
//!#[async_trait]
//!impl NewModel<Item, SaveQuery, AppState> for NewItem {
//!     async fn save(self: Self, _query: &SaveQuery, _state: &AppState) -> Result<Item> {
//!         // persist, and return Item entity
//!         let utc: DateTime<Utc> = Utc::now();
//!         Ok(Item{
//!             id: 1,
//!             content: self.content,
//!             created_at: Some(utc),
//!             deleted_at: None,
//!             updated_at: None,
//!         })
//!     }
//!}
//!
//!#[derive(Serialize, Deserialize, HttpUpdate)]
//!#[http_update(Id, UpdateQuery, Item, FindQuery, AppState)]
//!struct UpdatableItem {
//!     id: Id,
//!     content: String,
//!     updated_at: Option<DateTime<Utc>>,
//!}
//!#[async_trait]
//!impl UpdatableModel<UpdatableItem, UpdateQuery, AppState> for UpdatableItem {
//!     async fn update(mut self: Self, _query: &UpdateQuery, _state: &AppState) -> Result<UpdatableItem> {
//!         // update in db
//!         let utc: DateTime<Utc> = Utc::now();
//!         self.updated_at = Some(utc);
//!         Ok(self)
//!     }
//!}
//!
//!#[actix_web::main]
//!async fn main() -> std::io::Result<()>{
//!     actix_web::HttpServer::new(|| {
//!         actix_web::App::new()
//!         .service(actix_web::web::scope("/v1").configure(gen_endpoint!(Item, NewItem, UpdatableItem)))
//!         .app_data(actix_web::web::Data::new(AppState{}))
//!     })
//!     .bind(("127.0.0.1", 8085))?
//!     .run()
//!     .await
//!}
//! ```

use actix_web::{web, HttpResponse};
use anyhow::Result;

#[cfg(feature = "openapi")]
pub mod openapi;

// The derive macros share their names with the traits they implement, like serde's
// `Serialize`: `use actix_restful::HttpCreate;` imports both.
pub use actix_restful_derive::{actix_restful_info, HttpCreate, HttpFindListDelete, HttpUpdate};
// Implement `Model`, `NewModel` and `UpdatableModel` with sqlx queries, see the README
#[cfg(feature = "sqlx")]
pub use actix_restful_derive::{SqlxModel, SqlxNewModel, SqlxUpdatableModel};

// The traits are declared with `async_trait` and return `anyhow::Result`: their implementations
// need both, re-exported so that they do not have to be dependencies of the application.
pub use anyhow;
pub use async_trait::async_trait;

// Lets the code generated by the macros name this crate `::actix_restful` inside it too.
extern crate self as actix_restful;

/// Crates and functions used by the code generated by the macros, not part of the public API.
#[doc(hidden)]
pub mod __private {
    pub use actix_web;
    pub use async_trait::async_trait;
    pub use serde;
    #[cfg(feature = "sqlx")]
    pub use chrono;
    #[cfg(feature = "sqlx")]
    pub use sqlx;

    use crate::{HasMany, RestfulPathInfo};
    use actix_web::{web, HttpResponse};
    use serde::{de::DeserializeOwned, Deserialize, Serialize};

    /// The route of the relation `R`: `/{parent path}/{id}/{relation}`.
    pub fn relation_route<R: HasMany>() -> String {
        format!("/{}/{{id}}/{}", R::Parent::path(), R::RELATION)
    }

    #[derive(Deserialize)]
    pub struct RelationPath<ID> {
        id: ID,
    }

    /// The handler of the route of the relation `R`, registered by `gen_relation_endpoint!`.
    pub async fn http_list_related<R>(
        info: web::Path<RelationPath<R::Id>>,
        query: web::Query<R::Query>,
        state: web::Data<R::State>,
    ) -> HttpResponse
    where
        R: HasMany + 'static,
        R::Id: DeserializeOwned,
        R::Query: DeserializeOwned,
        R::Result: Serialize,
        R::State: 'static,
    {
        match R::list_related(info.into_inner().id, &query, &state).await {
            Ok(Some(res)) => HttpResponse::Ok().json(res),
            Ok(None) => HttpResponse::NotFound().body("ENTITY_NOT_FOUND"),
            Err(err) => HttpResponse::InternalServerError().body(err.to_string()),
        }
    }
}

/// A trait to implement on your main struct entity via the HttpFindListDelete derive macro :
///
/// ```ignore
///
/// use actix_restful::{
///  HttpFindListDelete,
///  Model,
///  actix_restful_info,
///  anyhow::Result,
///  async_trait,
/// };
///
/// #[derive(HttpFindListDelete)]
/// #[http_find_list_delete(Id, FindQuery, ListQuery, DeleteQuery, AppState)]
/// #[actix_restful_info(path = "item")]
/// struct Item {
/// }
///
/// #[async_trait]
/// impl Model<Id, FindQuery, ListQuery, ListResult, DeleteQuery, DeleteResult, AppState> for Item {
///    async fn find(id: Id, _query: &FindQuery, _state: &AppState) -> Result<Box<Item>> {
///    }
///    async fn list(_query: &ListQuery, _state: &AppState) -> Result<ListResult> {
///    }
///    async fn delete(mut self: Self, _query: &DeleteQuery, _state: &AppState) -> Result<DeleteResult> {
///    }
/// }
/// ```
#[async_trait]
pub trait Model<ID, FQ, LQ, LR, DQ, DR, AppState> {
    async fn find(id: ID, query: &FQ, state: &AppState) -> Result<Box<Self>>;
    async fn list(query: &LQ, state: &AppState) -> Result<LR>;
    async fn delete(self: Self, query: &DQ, state: &AppState) -> Result<DR>;
}

/// A trait to implement on your creatable entity entity
///
/// ```ignore
///
/// use actix_restful::{
///  HttpCreate,
///  NewModel,
///  anyhow::Result,
///  async_trait,
/// };
///
/// #[derive(HttpCreate)]
/// #[http_create(SaveQuery, AppState)]
/// struct NewItem {
/// }
///
/// #[async_trait]
/// impl NewModel<Item, SaveQuery, AppState> for NewItem {
///    async fn save(self: Self, _query: &SaveQuery, _state: &AppState) -> Result<Item> {
///    }
/// }
/// ```
#[async_trait]
pub trait NewModel<T, Q, AppState> {
    async fn save(self: Self, query: &Q, state: &AppState) -> Result<T>;
}

/// A trait to implement on your Updatable entity
///
/// ```ignore
///
/// use actix_restful::{
///  HttpUpdate,
///  UpdatableModel,
///  anyhow::Result,
///  async_trait,
/// };
///
/// #[derive(HttpUpdate)]
/// #[http_update(Id, UpdateQuery, Item, FindQuery, AppState)]
/// struct UpdatableItem {
/// }
///
/// #[async_trait]
/// impl UpdatableModel<UpdatableItem, UpdateQuery, AppState> for UpdatableItem {
///     async fn update(mut self: Self, _query: &UpdateQuery, _state: &AppState) -> Result<UpdatableItem> {
///     }
/// }
/// ```
#[async_trait]
pub trait UpdatableModel<T, Q, AppState> {
    async fn update(self: Self, query: &Q, state: &AppState) -> Result<T>;
}

/// A transformation of the payload before it is written, called by the `save` of `SqlxNewModel`
/// and the `update` of `SqlxUpdatableModel` when the struct has the `before_save` option
/// of `#[sqlx_model(...)]`. An error aborts the query and answers 500.
///
/// ```ignore
///
/// use actix_restful::{BeforeSave, anyhow::Result, async_trait};
///
/// #[derive(HttpCreate, SqlxNewModel)]
/// #[http_create(SaveQuery, AppState)]
/// #[sqlx_model(database = "postgres", model = "User", before_save)]
/// struct NewUser {
///     email: String,
///     password: String,
/// }
///
/// #[async_trait]
/// impl BeforeSave<AppState> for NewUser {
///     async fn before_save(mut self: Self, _state: &AppState) -> Result<Self> {
///         self.password = hash(&self.password)?;
///         Ok(self)
///     }
/// }
/// ```
#[async_trait]
pub trait BeforeSave<AppState>: Sized {
    async fn before_save(self: Self, state: &AppState) -> Result<Self>;
}

/// A has-many relation of a model, served on `GET /{path}/{id}/{RELATION}` by
/// `gen_relation_endpoint!`, `{path}` being the path of the parent model.
///
/// The trait is implemented on a type standing for the relation, so that a model can have
/// several relations, even towards the same child model:
///
/// ```ignore
///
/// use actix_restful::{HasMany, anyhow::Result, async_trait};
///
/// pub struct ProjectBooks;
///
/// #[async_trait]
/// impl HasMany for ProjectBooks {
///     type Parent = Project;
///     type Id = Id;
///     type Query = ProjectBooksQuery;
///     type Result = Vec<Book>;
///     type State = AppState;
///     const RELATION: &'static str = "books";
///
///     async fn list_related(id: Id, query: &ProjectBooksQuery, state: &AppState) -> Result<Option<Vec<Book>>> {
///         // `None` when no project has this id, the page of its books otherwise
///     }
/// }
/// ```
#[async_trait]
pub trait HasMany {
    /// The parent model, whose path prefixes the route
    type Parent: RestfulPathInfo;
    /// The id of the parent model
    type Id;
    /// The query string of the route, usually the pagination
    type Query;
    /// The response of the route, usually `Vec<Child>`
    type Result;
    type State;
    /// The last segment of the route, e.g. `books`
    const RELATION: &'static str;

    /// Lists the children of the parent `id`, `None` when the parent does not exist (404)
    async fn list_related(id: Self::Id, query: &Self::Query, state: &Self::State) -> Result<Option<Self::Result>>;
}

/// This Trait is automatically implemented with the `HttpCreate` derive macro

#[async_trait]
pub trait HttpCreate<Q, AppState> {
    /// This method is automaticaly implemented with the `HttpCreate` derive macro
    async fn http_create(
        payload: web::Json<Box<Self>>,
        query: web::Query<Q>,
        app_state: web::Data<AppState>,
    ) -> HttpResponse;
}

/// This Trait is automatically implemented with the `HttpFindListDelete` derive macro

#[async_trait]
pub trait HttpFindListDelete<P, FQ, LQ, DQ, AppState> {
    /// This method is automatically implemented with the `HttpFindListDelete` derive macro
    async fn http_find(
        info: web::Path<P>,
        query: web::Query<FQ>,
        app_state: web::Data<AppState>,
    ) -> HttpResponse;
    /// This method is automatically implemented with the `HttpFindListDelete` derive macro
    async fn http_list(
        query: web::Query<LQ>,
        app_state: web::Data<AppState>,
    ) -> HttpResponse;
    /// This method is automatically implemented with the `HttpFindListDelete` derive macro
    async fn http_delete(
        info: web::Path<P>,
        query: web::Query<DQ>,
        app_state: web::Data<AppState>,
    ) -> HttpResponse;
}

/// This Trait is automaticaly implemented with the `HttpUpdate` derive macro

#[async_trait]
pub trait HttpUpdate<P, Q, AppState> {
    /// This method is automaticaly implemented with the `HttpUpdate` derive macro
    async fn http_update(
        info: web::Path<P>,
        payload: web::Json<Box<Self>>,
        query: web::Query<Q>,
        app_state: web::Data<AppState>,
    ) -> HttpResponse;
}

pub trait RestfulPathInfo {
    fn path() -> String;
}

/// A macro to generate the http routes on the Actix app :
///
/// ```ignore
///
/// #[actix_web::main]
/// async fn main() -> std::io::Result<()>{
///    actix_web::HttpServer::new(|| {
///        actix_web::App::new()
///            .service(actix_web::web::scope("/v1").configure(gen_endpoint!(Item, NewItem, UpdatableItem)))
///            .app_data(actix_web::web::Data::new(AppState{}))
///    })
///        .bind(("127.0.0.1", 8085))?
///        .run()
///        .await
/// }
/// ```
///
/// If the attribute macro `actix_restful_info` is used with these parameters :
///
/// #[actix_restful_info(path = "item")]
///
///
/// The macro gen_endpoint! will generate 5 routes on the actix App :
///
/// - GET /v1/item/{id}
/// - GET /v1/item
/// - POST /v1/item
/// - PUT /v1/item/{id}
/// - DELETE /v1/item/{id}

#[macro_export]
macro_rules! gen_endpoint {
    ($model:ident, $new_model:ident, $updatable_model:ident) => {{
        let path = <$model as $crate::RestfulPathInfo>::path();
        use $crate::__private::actix_web::web;
        move |cfg: &mut web::ServiceConfig| {
            cfg.route(
                "/{path}/{id}".replace("{path}", &path).as_str(),
                web::get().to(<$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_find),
            )
            .route(
                "/{path}/{id}".replace("{path}", &path).as_str(),
                web::delete().to(<$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_delete),
            )
            .route(
                "/{path}/{id}".replace("{path}", &path).as_str(),
                web::put().to(<$updatable_model as $crate::HttpUpdate<_, _, _>>::http_update),
            )
            .route(
                "/{path}".replace("{path}", &path).as_str(),
                web::get().to(<$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_list),
            )
            .route(
                "/{path}".replace("{path}", &path).as_str(),
                web::post().to(<$new_model as $crate::HttpCreate<_, _>>::http_create),
            );
        }
    }};
}

/// Same as `gen_endpoint!`, on an [apistos](https://docs.rs/apistos) app: the 5 routes are
/// added to its OpenAPI document (requires the `openapi` feature).
///
/// The models, their query structs and the list / delete results must implement
/// `apistos::ApiComponent` (usually `#[derive(JsonSchema, ApiComponent)]`).
///
/// ```ignore
///
/// use apistos::app::OpenApiWrapper;
/// use apistos::spec::Spec;
///
/// #[actix_web::main]
/// async fn main() -> std::io::Result<()>{
///    actix_web::HttpServer::new(|| {
///        actix_web::App::new()
///            .document(Spec::default())
///            .service(apistos::web::scope("/v1").configure(gen_documented_endpoint!(Item, NewItem, UpdatableItem)))
///            .app_data(actix_web::web::Data::new(AppState{}))
///            .build("/openapi.json")
///    })
///        .bind(("127.0.0.1", 8085))?
///        .run()
///        .await
/// }
/// ```
#[cfg(feature = "openapi")]
#[macro_export]
macro_rules! gen_documented_endpoint {
    ($model:ident, $new_model:ident, $updatable_model:ident) => {{
        let path = <$model as $crate::RestfulPathInfo>::path();
        use std::marker::PhantomData;
        use $crate::openapi::{self, apistos::web};
        move |cfg: &mut web::ServiceConfig| {
            let item_path = "/{path}/{id}".replace("{path}", &path);
            let collection_path = "/{path}".replace("{path}", &path);
            cfg.route(
                &item_path,
                web::get().to(openapi::find(
                    PhantomData::<$model>,
                    <$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_find,
                )),
            )
            .route(
                &item_path,
                web::delete().to(openapi::delete(
                    PhantomData::<$model>,
                    <$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_delete,
                )),
            )
            .route(
                &item_path,
                web::put().to(openapi::update(
                    PhantomData::<($model, $updatable_model)>,
                    <$updatable_model as $crate::HttpUpdate<_, _, _>>::http_update,
                )),
            )
            .route(
                &collection_path,
                web::get().to(openapi::list(
                    PhantomData::<$model>,
                    <$model as $crate::HttpFindListDelete<_, _, _, _, _>>::http_list,
                )),
            )
            .route(
                &collection_path,
                web::post().to(openapi::create(
                    PhantomData::<($model, $new_model)>,
                    <$new_model as $crate::HttpCreate<_, _>>::http_create,
                )),
            );
        }
    }};
}

/// A macro to generate the route of a `HasMany` relation on the Actix app, to register in the
/// same scope as the parent model (Actix does not fall through between scopes sharing a prefix):
///
/// ```ignore
///
/// actix_web::web::scope("/v1")
///     .configure(gen_endpoint!(Project, NewProject, UpdatableProject))
///     .configure(gen_relation_endpoint!(ProjectBooks))
/// ```
///
/// With `RELATION = "books"` on a relation whose parent has the path `project`, the macro
/// generates the route:
///
/// - GET /v1/project/{id}/books
#[macro_export]
macro_rules! gen_relation_endpoint {
    ($relation:ty) => {{
        use $crate::__private::actix_web::web;
        move |cfg: &mut web::ServiceConfig| {
            cfg.route(
                &$crate::__private::relation_route::<$relation>(),
                web::get().to($crate::__private::http_list_related::<$relation>),
            );
        }
    }};
}

/// Same as `gen_relation_endpoint!`, on an [apistos](https://docs.rs/apistos) app: the route is
/// added to its OpenAPI document, tagged with the path of the parent model (requires the
/// `openapi` feature).
///
/// The id, query and result types of the relation must implement `apistos::ApiComponent`.
#[cfg(feature = "openapi")]
#[macro_export]
macro_rules! gen_documented_relation_endpoint {
    ($relation:ty) => {{
        use std::marker::PhantomData;
        use $crate::openapi::{self, apistos::web};
        move |cfg: &mut web::ServiceConfig| {
            cfg.route(
                &$crate::__private::relation_route::<$relation>(),
                web::get().to(openapi::list_related(
                    PhantomData::<$relation>,
                    $crate::__private::http_list_related::<$relation>,
                )),
            );
        }
    }};
}
