//! Tests of the OpenAPI document built by apistos for the routes generated by
//! `gen_documented_endpoint!`.
//! Query fields are only read by the extractors, to be documented.
#![allow(dead_code)]

use octopux::{
    octopux_info, gen_documented_endpoint, gen_documented_relation_endpoint, HasMany,
    HttpCreate, HttpFindListDelete, HttpUpdate, Model, NewModel, UpdatableModel,
};
use actix_web::{http::StatusCode, test, web, App};
use anyhow::{anyhow, Result};
use apistos::app::OpenApiWrapper;
use apistos::info::Info;
use apistos::spec::Spec;
use apistos::ApiComponent;
use async_trait::async_trait;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};

type Id = i64;

struct AppState {}

#[derive(Default, Deserialize, JsonSchema, ApiComponent)]
struct FindQuery {
    expand: Option<String>,
}
#[derive(Deserialize, JsonSchema, ApiComponent)]
struct ListQuery {
    offset: usize,
    limit: usize,
}
#[derive(Deserialize, JsonSchema, ApiComponent)]
struct DeleteQuery {}
#[derive(Deserialize, JsonSchema, ApiComponent)]
struct SaveQuery {}
#[derive(Deserialize, JsonSchema, ApiComponent)]
struct UpdateQuery {}

#[derive(Clone, Default, Serialize, Deserialize, JsonSchema, ApiComponent, HttpFindListDelete)]
#[http_find_list_delete(Id, FindQuery, ListQuery, DeleteQuery, AppState)]
#[octopux_info(path = "item")]
struct Item {
    id: Id,
    content: String,
}

#[async_trait]
impl Model<Id, FindQuery, ListQuery, Vec<Item>, DeleteQuery, Item, AppState> for Item {
    async fn find(id: Id, _query: &FindQuery, _state: &AppState) -> Result<Box<Item>> {
        match id {
            1 => Ok(Box::new(Item { id, content: "one".into() })),
            _ => Err(anyhow!("item {} not found", id)),
        }
    }
    async fn list(_query: &ListQuery, _state: &AppState) -> Result<Vec<Item>> {
        Ok(vec![])
    }
    async fn delete(self: Self, _query: &DeleteQuery, _state: &AppState) -> Result<Item> {
        Ok(self)
    }
}

#[derive(Serialize, Deserialize, JsonSchema, ApiComponent, HttpCreate)]
#[http_create(SaveQuery, AppState)]
struct NewItem {
    content: String,
}

#[async_trait]
impl NewModel<Item, SaveQuery, AppState> for NewItem {
    async fn save(self: Self, _query: &SaveQuery, _state: &AppState) -> Result<Item> {
        Ok(Item { id: 2, content: self.content })
    }
}

#[derive(Serialize, Deserialize, JsonSchema, ApiComponent, HttpUpdate)]
#[http_update(Id, UpdateQuery, Item, FindQuery, AppState)]
struct UpdatableItem {
    id: Id,
    content: String,
}

#[async_trait]
impl UpdatableModel<UpdatableItem, UpdateQuery, AppState> for UpdatableItem {
    async fn update(self: Self, _query: &UpdateQuery, _state: &AppState) -> Result<UpdatableItem> {
        Ok(self)
    }
}

#[derive(Serialize, JsonSchema, ApiComponent)]
struct Note {
    id: Id,
    text: String,
}

#[derive(Deserialize, JsonSchema, ApiComponent)]
struct ItemNotesQuery {
    offset: Option<usize>,
    limit: Option<usize>,
}

struct ItemNotes;

#[async_trait]
impl HasMany for ItemNotes {
    type Parent = Item;
    type Id = Id;
    type Query = ItemNotesQuery;
    type Result = Vec<Note>;
    type State = AppState;
    const RELATION: &'static str = "notes";

    async fn list_related(id: Id, _query: &ItemNotesQuery, _state: &AppState) -> Result<Option<Vec<Note>>> {
        match id {
            1 => Ok(Some(vec![Note { id: 1, text: "note".into() }])),
            _ => Ok(None),
        }
    }
}

macro_rules! init {
    () => {
        test::init_service(
            App::new()
                .document(Spec {
                    info: Info {
                        title: "items".into(),
                        version: "1.0.0".into(),
                        ..Default::default()
                    },
                    ..Default::default()
                })
                .app_data(web::Data::new(AppState {}))
                .service(
                    apistos::web::scope("/v1")
                        .configure(gen_documented_endpoint!(Item, NewItem, UpdatableItem))
                        .configure(gen_documented_relation_endpoint!(ItemNotes)),
                )
                .build("/openapi.json"),
        )
        .await
    };
}

async fn openapi() -> Value {
    let app = init!();
    let req = test::TestRequest::get().uri("/openapi.json").to_request();
    test::call_and_read_body_json(&app, req).await
}

fn parameter_names(operation: &Value) -> Vec<(&str, &str)> {
    operation["parameters"]
        .as_array()
        .map(|parameters| {
            parameters
                .iter()
                .map(|p| (p["in"].as_str().unwrap(), p["name"].as_str().unwrap()))
                .collect()
        })
        .unwrap_or_default()
}

fn response_codes(operation: &Value) -> Vec<&str> {
    operation["responses"].as_object().unwrap().keys().map(String::as_str).collect()
}

#[actix_web::test]
async fn documented_routes_still_serve_requests() {
    let app = init!();

    let req = test::TestRequest::get().uri("/v1/item/1").to_request();
    let body: Value = test::call_and_read_body_json(&app, req).await;
    assert_eq!(body, json!({ "id": 1, "content": "one" }));

    let req = test::TestRequest::get().uri("/v1/item/3").to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
}

#[actix_web::test]
async fn documented_relation_serves_requests() {
    let app = init!();

    let req = test::TestRequest::get().uri("/v1/item/1/notes").to_request();
    let body: Value = test::call_and_read_body_json(&app, req).await;
    assert_eq!(body, json!([{ "id": 1, "text": "note" }]));

    let req = test::TestRequest::get().uri("/v1/item/3/notes").to_request();
    let resp = test::call_service(&app, req).await;
    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
}

#[actix_web::test]
async fn documents_the_generated_routes() {
    let doc = openapi().await;
    let paths = doc["paths"].as_object().unwrap();

    let mut documented: Vec<(String, String)> = paths
        .iter()
        .flat_map(|(path, item)| {
            item.as_object()
                .unwrap()
                .keys()
                .map(move |method| (path.clone(), method.clone()))
        })
        .collect();
    documented.sort();
    let expected: Vec<(String, String)> = [
        ("/v1/item", "get"),
        ("/v1/item", "post"),
        ("/v1/item/{id}", "delete"),
        ("/v1/item/{id}", "get"),
        ("/v1/item/{id}", "put"),
        ("/v1/item/{id}/notes", "get"),
    ]
    .iter()
    .map(|(p, m)| (p.to_string(), m.to_string()))
    .collect();
    assert_eq!(documented, expected);
}

#[actix_web::test]
async fn operations_are_tagged_and_identified_by_model_path() {
    let doc = openapi().await;
    let ids = [
        ("/v1/item/{id}", "get", "find_item"),
        ("/v1/item/{id}", "delete", "delete_item"),
        ("/v1/item/{id}", "put", "update_item"),
        ("/v1/item", "get", "list_item"),
        ("/v1/item", "post", "create_item"),
    ];
    for (path, method, id) in ids {
        let operation = &doc["paths"][path][method];
        assert_eq!(operation["operationId"], id, "{} {}", method, path);
        assert_eq!(operation["tags"], json!(["item"]), "{} {}", method, path);
    }
}

#[actix_web::test]
async fn find_documents_path_and_query_parameters_and_responses() {
    let doc = openapi().await;
    let find = &doc["paths"]["/v1/item/{id}"]["get"];

    assert_eq!(parameter_names(find), [("path", "id"), ("query", "expand")]);
    assert_eq!(find["parameters"][0]["schema"]["type"], "integer");
    assert_eq!(find["parameters"][0]["required"], true);
    assert_eq!(response_codes(find), ["200", "404"]);
    assert_eq!(
        find["responses"]["200"]["content"]["application/json"]["schema"],
        json!({ "$ref": "#/components/schemas/Item" })
    );
}

#[actix_web::test]
async fn list_documents_an_inline_array_of_models() {
    let doc = openapi().await;
    let list = &doc["paths"]["/v1/item"]["get"];

    assert_eq!(parameter_names(list), [("query", "limit"), ("query", "offset")]);
    assert_eq!(response_codes(list), ["200", "500"]);
    assert_eq!(
        list["responses"]["200"]["content"]["application/json"]["schema"],
        json!({ "type": "array", "items": { "$ref": "#/components/schemas/Item" } })
    );
}

#[actix_web::test]
async fn relation_is_tagged_with_the_parent_path_and_documents_its_parameters() {
    let doc = openapi().await;
    let relation = &doc["paths"]["/v1/item/{id}/notes"]["get"];

    assert_eq!(relation["operationId"], "list_item_notes");
    assert_eq!(relation["tags"], json!(["item"]));
    assert_eq!(
        parameter_names(relation),
        [("path", "id"), ("query", "limit"), ("query", "offset")]
    );
    assert_eq!(response_codes(relation), ["200", "404", "500"]);
    assert_eq!(
        relation["responses"]["200"]["content"]["application/json"]["schema"],
        json!({ "type": "array", "items": { "$ref": "#/components/schemas/Note" } })
    );
}

#[actix_web::test]
async fn create_and_update_document_their_payloads() {
    let doc = openapi().await;
    let create = &doc["paths"]["/v1/item"]["post"];
    let update = &doc["paths"]["/v1/item/{id}"]["put"];

    assert_eq!(
        create["requestBody"]["content"]["application/json"]["schema"],
        json!({ "$ref": "#/components/schemas/NewItem" })
    );
    assert_eq!(
        create["responses"]["200"]["content"]["application/json"]["schema"],
        json!({ "$ref": "#/components/schemas/Item" })
    );
    assert_eq!(
        update["requestBody"]["content"]["application/json"]["schema"],
        json!({ "$ref": "#/components/schemas/UpdatableItem" })
    );
    assert_eq!(parameter_names(update), [("path", "id")]);
    assert_eq!(response_codes(update), ["200", "400", "404", "500"]);
}

#[actix_web::test]
async fn components_hold_the_model_schemas() {
    let doc = openapi().await;
    let schemas = doc["components"]["schemas"].as_object().unwrap();

    let mut names: Vec<&str> = schemas.keys().map(String::as_str).collect();
    names.sort();
    assert_eq!(names, ["Item", "NewItem", "Note", "UpdatableItem"]);
    assert_eq!(schemas["Item"]["type"], "object");
    assert_eq!(schemas["Item"]["required"], json!(["content", "id"]));
}
