[package]
name = "octopux-derive"
version.workspace = true
edition.workspace = true
description = "Derive and procedural macros for octopux"
license.workspace = true
repository.workspace = true
authors.workspace = true
readme.workspace = true
keywords = ["actix", "crud", "rest", "derive", "macro"]
categories = ["web-programming::http-server", "development-tools::procedural-macro-helpers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
darling.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lib]
proc-macro = true
