//! OpenAPI documentation of the routes generated by `gen_documented_endpoint!`, built with
//! [apistos](https://docs.rs/apistos).
//!
//! The handlers generated by the derive macros are wrapped in [`Documented`], whose future
//! carries a [`PathItemDefinition`]: apistos reads it when the route is registered to add the
//! operation to the OpenAPI document. Operations are tagged and identified by the model path
//! given to `octopux_info`, so several models can be documented in the same app.
//!
//! Every type exposed by a route (models, query structs, list and delete results) must implement
//! [`ApiComponent`], usually with `#[derive(JsonSchema, ApiComponent)]` from apistos.

use crate::{HasMany, Model, NewModel, RestfulPathInfo, UpdatableModel};
use actix_web::{web, FromRequest, Handler, Responder};
use apistos::actix::ResponseWrapper;
use apistos::components::Components;
use apistos::paths::{MediaType, Operation, Response, Responses};
use apistos::reference_or::ReferenceOr;
use apistos::{ApiComponent, InstanceType, PathItemDefinition, Schema, SingleOrVec};
use std::collections::BTreeMap;
use std::marker::PhantomData;

pub use apistos;

/// A handler whose future documents the route it is registered on with the operation `D`.
pub struct Documented<F, D> {
    handler: F,
    doc: PhantomData<fn() -> D>,
}

impl<F: Clone, D> Clone for Documented<F, D> {
    fn clone(&self) -> Self {
        Documented {
            handler: self.handler.clone(),
            doc: PhantomData,
        }
    }
}

impl<F, D> Documented<F, D> {
    pub fn new(handler: F) -> Self {
        Documented {
            handler,
            doc: PhantomData,
        }
    }
}

impl<F, Args, D> Handler<Args> for Documented<F, D>
where
    F: Handler<Args>,
    Args: FromRequest,
    F::Output: Responder,
    D: PathItemDefinition + Default + 'static,
{
    type Output = F::Output;
    type Future = ResponseWrapper<F::Future, D>;

    fn call(&self, args: Args) -> Self::Future {
        ResponseWrapper {
            inner: self.handler.call(args),
            path_item: D::default(),
        }
    }
}

macro_rules! operation_struct {
    ($(#[$doc:meta])* $name:ident<$($param:ident),+>) => {
        $(#[$doc])*
        pub struct $name<$($param),+>(PhantomData<fn() -> ($($param,)+)>);

        impl<$($param),+> Default for $name<$($param),+> {
            fn default() -> Self {
                $name(PhantomData)
            }
        }
    };
}

operation_struct!(
    /// `GET /{path}/{id}`: finds the model `M` identified by `ID`.
    FindOperation<M, ID, FQ>
);
operation_struct!(
    /// `GET /{path}`: lists the models `M`, answering `LR`.
    ListOperation<M, LQ, LR>
);
operation_struct!(
    /// `DELETE /{path}/{id}`: deletes the model `M` identified by `ID`, answering `DR`.
    DeleteOperation<M, ID, DQ, DR>
);
operation_struct!(
    /// `POST /{path}`: saves the payload `N` as a model `M`, answering `T`.
    CreateOperation<M, N, SQ, T>
);
operation_struct!(
    /// `PUT /{path}/{id}`: updates the model `M` identified by `ID` with the payload `U`, answering `T`.
    UpdateOperation<M, ID, U, UQ, T>
);
operation_struct!(
    /// `GET /{path}/{id}/{relation}`: lists the children of the relation `R` of a parent model.
    ListRelatedOperation<R>
);

impl<M, ID, FQ> PathItemDefinition for FindOperation<M, ID, FQ>
where
    M: RestfulPathInfo + ApiComponent,
    ID: ApiComponent,
    FQ: ApiComponent,
{
    fn operation() -> Operation {
        let path = M::path();
        let mut operation = operation(
            &path,
            "find",
            format!("Find one {} by id", path),
            [web::Path::<ID>::parameters(), web::Query::<FQ>::parameters()],
        );
        add_response(&mut operation, "200", json_response::<M>(format!("The {} found", path)));
        add_response(&mut operation, "404", text_response("ENTITY_NOT_FOUND: no entity has this id"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<M>(), schemas::<web::Query<FQ>>()])
    }
}

impl<M, LQ, LR> PathItemDefinition for ListOperation<M, LQ, LR>
where
    M: RestfulPathInfo,
    LQ: ApiComponent,
    LR: ApiComponent,
{
    fn operation() -> Operation {
        let path = M::path();
        let mut operation = operation(
            &path,
            "list",
            format!("List the {} entities", path),
            [web::Query::<LQ>::parameters()],
        );
        add_response(&mut operation, "200", json_response::<LR>(format!("The {} entities", path)));
        add_response(&mut operation, "500", text_response("The listing failed"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<LR>(), schemas::<web::Query<LQ>>()])
    }
}

impl<M, ID, DQ, DR> PathItemDefinition for DeleteOperation<M, ID, DQ, DR>
where
    M: RestfulPathInfo,
    ID: ApiComponent,
    DQ: ApiComponent,
    DR: ApiComponent,
{
    fn operation() -> Operation {
        let path = M::path();
        let mut operation = operation(
            &path,
            "delete",
            format!("Delete one {} by id", path),
            [web::Path::<ID>::parameters(), web::Query::<DQ>::parameters()],
        );
        add_response(&mut operation, "200", json_response::<DR>(format!("The deleted {}", path)));
        add_response(&mut operation, "404", text_response("ENTITY_NOT_FOUND: no entity has this id"));
        add_response(&mut operation, "500", text_response("The deletion failed"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<DR>(), schemas::<web::Query<DQ>>()])
    }
}

impl<M, N, SQ, T> PathItemDefinition for CreateOperation<M, N, SQ, T>
where
    M: RestfulPathInfo,
    N: ApiComponent,
    SQ: ApiComponent,
    T: ApiComponent,
{
    fn operation() -> Operation {
        let path = M::path();
        let mut operation = operation(
            &path,
            "create",
            format!("Create one {}", path),
            [web::Query::<SQ>::parameters()],
        );
        operation.request_body = web::Json::<N>::request_body().map(ReferenceOr::Object);
        add_response(&mut operation, "200", json_response::<T>(format!("The created {}", path)));
        add_response(&mut operation, "500", text_response("The creation failed"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<N>(), schemas::<T>(), schemas::<web::Query<SQ>>()])
    }
}

impl<M, ID, U, UQ, T> PathItemDefinition for UpdateOperation<M, ID, U, UQ, T>
where
    M: RestfulPathInfo,
    ID: ApiComponent,
    U: ApiComponent,
    UQ: ApiComponent,
    T: ApiComponent,
{
    fn operation() -> Operation {
        let path = M::path();
        let mut operation = operation(
            &path,
            "update",
            format!("Update one {} by id", path),
            [web::Path::<ID>::parameters(), web::Query::<UQ>::parameters()],
        );
        operation.request_body = web::Json::<U>::request_body().map(ReferenceOr::Object);
        add_response(&mut operation, "200", json_response::<T>(format!("The updated {}", path)));
        add_response(&mut operation, "400", text_response("ID_MISMATCH: the payload id differs from the path id"));
        add_response(&mut operation, "404", text_response("ENTITY_NOT_FOUND: no entity has this id"));
        add_response(&mut operation, "500", text_response("The update failed"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<U>(), schemas::<T>(), schemas::<web::Query<UQ>>()])
    }
}

impl<R> PathItemDefinition for ListRelatedOperation<R>
where
    R: HasMany,
    R::Id: ApiComponent,
    R::Query: ApiComponent,
    R::Result: ApiComponent,
{
    fn operation() -> Operation {
        let path = R::Parent::path();
        let mut operation = operation(
            &path,
            "list",
            format!("List the {} of one {} by id", R::RELATION, path),
            [web::Path::<R::Id>::parameters(), web::Query::<R::Query>::parameters()],
        );
        // Unique among the relations of the model: `list_{path}_{relation}`
        operation.operation_id = Some(operation_id("list", &format!("{}/{}", path, R::RELATION)));
        add_response(&mut operation, "200", json_response::<R::Result>(format!("The {} of the {}", R::RELATION, path)));
        add_response(&mut operation, "404", text_response("ENTITY_NOT_FOUND: no parent entity has this id"));
        add_response(&mut operation, "500", text_response("The listing failed"));
        operation
    }

    fn components() -> Vec<Components> {
        components(&[schemas::<R::Result>(), schemas::<web::Query<R::Query>>()])
    }
}

/// Documents the handler `HttpFindListDelete::http_find` of the model `M`.
pub fn find<M, ID, FQ, LQ, LR, DQ, DR, S, F>(_: PhantomData<M>, handler: F) -> Documented<F, FindOperation<M, ID, FQ>>
where
    M: Model<ID, FQ, LQ, LR, DQ, DR, S>,
{
    Documented::new(handler)
}

/// Documents the handler `HttpFindListDelete::http_list` of the model `M`.
pub fn list<M, ID, FQ, LQ, LR, DQ, DR, S, F>(_: PhantomData<M>, handler: F) -> Documented<F, ListOperation<M, LQ, LR>>
where
    M: Model<ID, FQ, LQ, LR, DQ, DR, S>,
{
    Documented::new(handler)
}

/// Documents the handler `HttpFindListDelete::http_delete` of the model `M`.
pub fn delete<M, ID, FQ, LQ, LR, DQ, DR, S, F>(
    _: PhantomData<M>,
    handler: F,
) -> Documented<F, DeleteOperation<M, ID, DQ, DR>>
where
    M: Model<ID, FQ, LQ, LR, DQ, DR, S>,
{
    Documented::new(handler)
}

/// Documents the handler `HttpCreate::http_create` of the creatable model `N` of `M`.
pub fn create<M, N, SQ, T, S, F>(_: PhantomData<(M, N)>, handler: F) -> Documented<F, CreateOperation<M, N, SQ, T>>
where
    N: NewModel<T, SQ, S>,
{
    Documented::new(handler)
}

/// Documents the handler `HttpUpdate::http_update` of the updatable model `U` of `M`.
pub fn update<M, U, ID, FQ, LQ, LR, DQ, DR, UQ, T, S, F>(
    _: PhantomData<(M, U)>,
    handler: F,
) -> Documented<F, UpdateOperation<M, ID, U, UQ, T>>
where
    M: Model<ID, FQ, LQ, LR, DQ, DR, S>,
    U: UpdatableModel<T, UQ, S>,
{
    Documented::new(handler)
}

/// Documents the handler `http_list_related` of the relation `R`.
pub fn list_related<R: HasMany, F>(_: PhantomData<R>, handler: F) -> Documented<F, ListRelatedOperation<R>> {
    Documented::new(handler)
}

fn operation<const N: usize>(
    path: &str,
    action: &str,
    summary: String,
    parameters: [Vec<apistos::paths::Parameter>; N],
) -> Operation {
    Operation {
        tags: vec![path.to_string()],
        summary: Some(summary),
        operation_id: Some(operation_id(action, path)),
        parameters: parameters.into_iter().flatten().map(ReferenceOr::Object).collect(),
        ..Default::default()
    }
}

/// Operation ids must be unique in the document: they are made of the action and the model path.
fn operation_id(action: &str, path: &str) -> String {
    let path: String = path
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    format!("{}_{}", action, path.trim_matches('_'))
}

fn add_response(operation: &mut Operation, status: &str, response: Response) {
    let responses: &mut Responses = &mut operation.responses;
    responses.responses.insert(status.to_string(), ReferenceOr::Object(response));
}

fn json_response<T: ApiComponent>(description: String) -> Response {
    let schema = match T::schema() {
        // Arrays (`Vec<T>`) are inlined, other named schemas are referenced from the components.
        Some((_, ReferenceOr::Object(schema))) if is_array(&schema) => Some(ReferenceOr::Object(schema)),
        Some((_, reference @ ReferenceOr::Reference { .. })) => Some(reference),
        Some((name, ReferenceOr::Object(_))) => Some(ReferenceOr::Reference {
            _ref: format!("#/components/schemas/{}", name),
        }),
        None => T::raw_schema(),
    };
    Response {
        description,
        content: BTreeMap::from([(
            T::content_type(),
            MediaType {
                schema,
                ..Default::default()
            },
        )]),
        ..Default::default()
    }
}

fn text_response(description: &str) -> Response {
    Response {
        description: description.to_string(),
        content: BTreeMap::from([("text/plain".to_string(), MediaType::default())]),
        ..Default::default()
    }
}

fn is_array(schema: &Schema) -> bool {
    matches!(
        schema,
        Schema::Object(object)
            if object.instance_type == Some(SingleOrVec::Single(Box::new(InstanceType::Array)))
    )
}

type NamedSchema = (String, ReferenceOr<Schema>);

/// The named schemas `T` needs, itself included: `(top-level schemas, child schemas)`.
fn schemas<T: ApiComponent>() -> (Vec<NamedSchema>, Vec<NamedSchema>) {
    // `Vec<T>` names its inline array schema after `T`: keep it out of the components.
    let schema = T::schema().filter(|(_, schema)| !matches!(schema, ReferenceOr::Object(s) if is_array(s)));
    (schema.into_iter().collect(), T::child_schemas())
}

fn components(schemas: &[(Vec<NamedSchema>, Vec<NamedSchema>)]) -> Vec<Components> {
    let top_level = schemas.iter().flat_map(|(schemas, _)| schemas.iter().cloned());
    let children = schemas.iter().flat_map(|(_, children)| children.iter().cloned());
    vec![Components {
        schemas: top_level.chain(children).collect(),
        ..Default::default()
    }]
}

#[cfg(test)]
mod tests {
    use super::operation_id;

    #[test]
    fn operation_id_joins_action_and_path() {
        assert_eq!(operation_id("find", "item"), "find_item");
    }

    #[test]
    fn operation_id_replaces_non_alphanumeric_characters() {
        assert_eq!(operation_id("list", "/api/sub-item/"), "list_api_sub_item");
    }
}
