//! End-to-end tests of the routes generated by `gen_endpoint!` for models
//! deriving `HttpFindListDelete`, `HttpCreate` and `HttpUpdate`.

use actix_restful::{
    actix_restful_info, gen_endpoint, HttpCreate, HttpFindListDelete, HttpUpdate, Model, NewModel,
    RestfulPathInfo, UpdatableModel,
};
use actix_web::{
    body::MessageBody,
    dev::ServiceResponse,
    http::StatusCode,
    test, web, App,
};
use anyhow::{anyhow, Result};
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::atomic::{AtomicBool, AtomicUsize, Ordering};
use std::sync::Mutex;

type Id = i64;

/// In-memory storage, with switches to make each model operation fail.
#[derive(Default)]
struct AppState {
    items: Mutex<BTreeMap<Id, Item>>,
    fail_list: AtomicBool,
    fail_save: AtomicBool,
    fail_update: AtomicBool,
    fail_delete: AtomicBool,
    update_calls: AtomicUsize,
    last_find_query: Mutex<Option<FindQuery>>,
}

impl AppState {
    fn with_items(items: &[(Id, &str)]) -> web::Data<AppState> {
        let state = AppState::default();
        {
            let mut store = state.items.lock().unwrap();
            for (id, content) in items {
                store.insert(
                    *id,
                    Item {
                        id: *id,
                        content: content.to_string(),
                        deleted: false,
                    },
                );
            }
        }
        web::Data::new(state)
    }
}

#[derive(Default, Clone, Debug, PartialEq, Deserialize)]
struct FindQuery {
    expand: Option<String>,
}
#[derive(Deserialize)]
struct ListQuery {
    offset: usize,
    limit: usize,
}
#[derive(Deserialize)]
struct DeleteQuery {}
#[derive(Deserialize)]
struct SaveQuery {
    prefix: Option<String>,
}
#[derive(Deserialize)]
struct UpdateQuery {}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
struct ListResult {
    offset: usize,
    limit: usize,
    results: Vec<Item>,
}

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize, HttpFindListDelete)]
#[http_find_list_delete(Id, FindQuery, ListQuery, DeleteQuery, AppState)]
#[actix_restful_info(path = "item")]
struct Item {
    id: Id,
    content: String,
    deleted: bool,
}

#[async_trait]
impl Model<Id, FindQuery, ListQuery, ListResult, DeleteQuery, Item, AppState> for Item {
    async fn find(id: Id, query: &FindQuery, state: &AppState) -> Result<Box<Item>> {
        *state.last_find_query.lock().unwrap() = Some(query.clone());
        state
            .items
            .lock()
            .unwrap()
            .get(&id)
            .cloned()
            .map(Box::new)
            .ok_or_else(|| anyhow!("item {} not found", id))
    }

    async fn list(query: &ListQuery, state: &AppState) -> Result<ListResult> {
        if state.fail_list.load(Ordering::SeqCst) {
            return Err(anyhow!("list failed"));
        }
        let results = state
            .items
            .lock()
            .unwrap()
            .values()
            .skip(query.offset)
            .take(query.limit)
            .cloned()
            .collect();
        Ok(ListResult {
            offset: query.offset,
            limit: query.limit,
            results,
        })
    }

    async fn delete(mut self: Self, _query: &DeleteQuery, state: &AppState) -> Result<Item> {
        if state.fail_delete.load(Ordering::SeqCst) {
            return Err(anyhow!("delete failed"));
        }
        state.items.lock().unwrap().remove(&self.id);
        self.deleted = true;
        Ok(self)
    }
}

#[derive(Serialize, Deserialize, HttpCreate)]
#[http_create(SaveQuery, AppState)]
struct NewItem {
    content: String,
}

#[async_trait]
impl NewModel<Item, SaveQuery, AppState> for NewItem {
    async fn save(self: Self, query: &SaveQuery, state: &AppState) -> Result<Item> {
        if state.fail_save.load(Ordering::SeqCst) {
            return Err(anyhow!("save failed"));
        }
        let mut store = state.items.lock().unwrap();
        let id = store.keys().max().copied().unwrap_or(0) + 1;
        let item = Item {
            id,
            content: format!("{}{}", query.prefix.as_deref().unwrap_or(""), self.content),
            deleted: false,
        };
        store.insert(id, item.clone());
        Ok(item)
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize, HttpUpdate)]
#[http_update(Id, UpdateQuery, Item, FindQuery, AppState)]
struct UpdatableItem {
    id: Id,
    content: String,
}

#[async_trait]
impl UpdatableModel<UpdatableItem, UpdateQuery, AppState> for UpdatableItem {
    async fn update(self: Self, _query: &UpdateQuery, state: &AppState) -> Result<UpdatableItem> {
        state.update_calls.fetch_add(1, Ordering::SeqCst);
        if state.fail_update.load(Ordering::SeqCst) {
            return Err(anyhow!("update failed"));
        }
        let mut store = state.items.lock().unwrap();
        let item = store
            .get_mut(&self.id)
            .ok_or_else(|| anyhow!("item {} not found", self.id))?;
        item.content = self.content.clone();
        Ok(self)
    }
}

/// Builds the test service with the routes generated by `gen_endpoint!`.
macro_rules! init {
    ($state:expr) => {
        test::init_service(
            App::new()
                .app_data($state.clone())
                .service(web::scope("/v1").configure(gen_endpoint!(
                    Item,
                    NewItem,
                    UpdatableItem
                ))),
        )
        .await
    };
}

async fn body_string(resp: ServiceResponse<impl MessageBody>) -> String {
    String::from_utf8(test::read_body(resp).await.to_vec()).unwrap()
}

// ---------------------------------------------------------------------------
// actix_restful_info
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn restful_info_exposes_path() {
    assert_eq!(Item::path(), "item");
}

// ---------------------------------------------------------------------------
// GET /v1/item
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn list_returns_model_result_as_json() {
    let state = AppState::with_items(&[(1, "a"), (2, "b"), (3, "c")]);
    let app = init!(state);

    let req = test::TestRequest::get()
        .uri("/v1/item?offset=1&limit=1")
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    let body: ListResult = test::read_body_json(resp).await;
    assert_eq!(
        body,
        ListResult {
            offset: 1,
            limit: 1,
            results: vec![Item {
                id: 2,
                content: "b".into(),
                deleted: false
            }],
        }
    );
}

#[actix_web::test]
async fn list_rejects_invalid_query_string() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::get()
        .uri("/v1/item?offset=abc")
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
}

#[actix_web::test]
async fn list_error_returns_500_with_error_message() {
    let state = AppState::with_items(&[]);
    state.fail_list.store(true, Ordering::SeqCst);
    let app = init!(state);

    let req = test::TestRequest::get()
        .uri("/v1/item?offset=0&limit=10")
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::INTERNAL_SERVER_ERROR);
    assert_eq!(body_string(resp).await, "list failed");
}

// ---------------------------------------------------------------------------
// GET /v1/item/{id}
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn find_returns_entity_as_json() {
    let state = AppState::with_items(&[(7, "seven")]);
    let app = init!(state);

    let req = test::TestRequest::get().uri("/v1/item/7").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    let body: Item = test::read_body_json(resp).await;
    assert_eq!(
        body,
        Item {
            id: 7,
            content: "seven".into(),
            deleted: false
        }
    );
}

#[actix_web::test]
async fn find_forwards_query_string_to_model() {
    let state = AppState::with_items(&[(7, "seven")]);
    let app = init!(state);

    let req = test::TestRequest::get()
        .uri("/v1/item/7?expand=owner")
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    assert_eq!(
        *state.last_find_query.lock().unwrap(),
        Some(FindQuery {
            expand: Some("owner".into())
        })
    );
}

#[actix_web::test]
async fn find_unknown_id_returns_404() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::get().uri("/v1/item/42").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    assert_eq!(body_string(resp).await, "ENTITY_NOT_FOUND");
}

#[actix_web::test]
async fn find_with_malformed_id_returns_404() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::get().uri("/v1/item/not-a-number").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
}

// ---------------------------------------------------------------------------
// POST /v1/item
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn create_saves_and_returns_entity() {
    let state = AppState::with_items(&[(1, "a")]);
    let app = init!(state);

    let req = test::TestRequest::post()
        .uri("/v1/item")
        .set_json(serde_json::json!({ "content": "new" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    let body: Item = test::read_body_json(resp).await;
    let expected = Item {
        id: 2,
        content: "new".into(),
        deleted: false,
    };
    assert_eq!(body, expected);
    assert_eq!(state.items.lock().unwrap().get(&2), Some(&expected));
}

#[actix_web::test]
async fn create_forwards_query_string_to_model() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::post()
        .uri("/v1/item?prefix=pre-")
        .set_json(serde_json::json!({ "content": "new" }))
        .to_request();
    let body: Item = test::call_and_read_body_json(&app, req).await;

    assert_eq!(body.content, "pre-new");
}

#[actix_web::test]
async fn create_with_invalid_payload_returns_400() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::post()
        .uri("/v1/item")
        .set_json(serde_json::json!({ "wrong_field": 1 }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    assert!(state.items.lock().unwrap().is_empty());
}

#[actix_web::test]
async fn create_error_returns_500_with_error_message() {
    let state = AppState::with_items(&[]);
    state.fail_save.store(true, Ordering::SeqCst);
    let app = init!(state);

    let req = test::TestRequest::post()
        .uri("/v1/item")
        .set_json(serde_json::json!({ "content": "new" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::INTERNAL_SERVER_ERROR);
    assert_eq!(body_string(resp).await, "save failed");
}

// ---------------------------------------------------------------------------
// PUT /v1/item/{id}
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn update_existing_entity_returns_updated_entity() {
    let state = AppState::with_items(&[(3, "old")]);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3")
        .set_json(serde_json::json!({ "id": 3, "content": "updated" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    let body: UpdatableItem = test::read_body_json(resp).await;
    assert_eq!(
        body,
        UpdatableItem {
            id: 3,
            content: "updated".into()
        }
    );
    assert_eq!(state.items.lock().unwrap()[&3].content, "updated");
}

#[actix_web::test]
async fn update_unknown_id_returns_404_without_calling_update() {
    let state = AppState::with_items(&[]);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3")
        .set_json(serde_json::json!({ "id": 3, "content": "updated" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    assert_eq!(body_string(resp).await, "ENTITY_NOT_FOUND");
    assert_eq!(state.update_calls.load(Ordering::SeqCst), 0);
}

#[actix_web::test]
async fn update_with_payload_id_different_from_path_id_returns_400() {
    let state = AppState::with_items(&[(3, "three"), (5, "five")]);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3")
        .set_json(serde_json::json!({ "id": 5, "content": "updated" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    assert_eq!(body_string(resp).await, "ID_MISMATCH");
    assert_eq!(state.update_calls.load(Ordering::SeqCst), 0);
    let items = state.items.lock().unwrap();
    assert_eq!(items[&3].content, "three");
    assert_eq!(items[&5].content, "five");
}

#[actix_web::test]
async fn update_uses_default_find_query() {
    let state = AppState::with_items(&[(3, "old")]);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3?expand=owner")
        .set_json(serde_json::json!({ "id": 3, "content": "updated" }))
        .to_request();
    test::call_service(&app, req).await;

    assert_eq!(
        *state.last_find_query.lock().unwrap(),
        Some(FindQuery::default())
    );
}

#[actix_web::test]
async fn update_with_invalid_payload_returns_400() {
    let state = AppState::with_items(&[(3, "old")]);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3")
        .set_json(serde_json::json!({ "content": 12 }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    assert_eq!(state.update_calls.load(Ordering::SeqCst), 0);
    assert_eq!(state.items.lock().unwrap()[&3].content, "old");
}

#[actix_web::test]
async fn update_error_returns_500_with_error_message() {
    let state = AppState::with_items(&[(3, "old")]);
    state.fail_update.store(true, Ordering::SeqCst);
    let app = init!(state);

    let req = test::TestRequest::put()
        .uri("/v1/item/3")
        .set_json(serde_json::json!({ "id": 3, "content": "updated" }))
        .to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::INTERNAL_SERVER_ERROR);
    assert_eq!(body_string(resp).await, "update failed");
    assert_eq!(state.items.lock().unwrap()[&3].content, "old");
}

// ---------------------------------------------------------------------------
// DELETE /v1/item/{id}
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn delete_existing_entity_returns_delete_result() {
    let state = AppState::with_items(&[(5, "five")]);
    let app = init!(state);

    let req = test::TestRequest::delete().uri("/v1/item/5").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::OK);
    let body: Item = test::read_body_json(resp).await;
    assert_eq!(
        body,
        Item {
            id: 5,
            content: "five".into(),
            deleted: true
        }
    );
    assert!(state.items.lock().unwrap().is_empty());
}

#[actix_web::test]
async fn delete_unknown_id_returns_404() {
    let state = AppState::with_items(&[(5, "five")]);
    let app = init!(state);

    let req = test::TestRequest::delete().uri("/v1/item/6").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    assert_eq!(body_string(resp).await, "ENTITY_NOT_FOUND");
    assert_eq!(state.items.lock().unwrap().len(), 1);
}

#[actix_web::test]
async fn delete_uses_default_find_query() {
    let state = AppState::with_items(&[(5, "five")]);
    let app = init!(state);

    let req = test::TestRequest::delete()
        .uri("/v1/item/5?expand=owner")
        .to_request();
    test::call_service(&app, req).await;

    assert_eq!(
        *state.last_find_query.lock().unwrap(),
        Some(FindQuery::default())
    );
}

#[actix_web::test]
async fn delete_error_returns_500_with_error_message() {
    let state = AppState::with_items(&[(5, "five")]);
    state.fail_delete.store(true, Ordering::SeqCst);
    let app = init!(state);

    let req = test::TestRequest::delete().uri("/v1/item/5").to_request();
    let resp = test::call_service(&app, req).await;

    assert_eq!(resp.status(), StatusCode::INTERNAL_SERVER_ERROR);
    assert_eq!(body_string(resp).await, "delete failed");
    assert_eq!(state.items.lock().unwrap().len(), 1);
}

// ---------------------------------------------------------------------------
// Routing
// ---------------------------------------------------------------------------

#[actix_web::test]
async fn routes_outside_scope_are_not_registered() {
    let state = AppState::with_items(&[(1, "a")]);
    let app = init!(state);

    for uri in ["/item/1", "/v1/items/1", "/v2/item/1"] {
        let req = test::TestRequest::get().uri(uri).to_request();
        let resp = test::call_service(&app, req).await;
        assert_eq!(resp.status(), StatusCode::NOT_FOUND, "GET {}", uri);
    }
}

#[actix_web::test]
async fn unsupported_methods_are_not_routed_to_handlers() {
    let state = AppState::with_items(&[(1, "a")]);
    let app = init!(state);

    let patch = test::TestRequest::patch().uri("/v1/item/1").to_request();
    assert!(test::call_service(&app, patch).await.status().is_client_error());

    let post_on_id = test::TestRequest::post()
        .uri("/v1/item/1")
        .set_json(serde_json::json!({ "content": "x" }))
        .to_request();
    assert!(test::call_service(&app, post_on_id)
        .await
        .status()
        .is_client_error());

    assert_eq!(state.items.lock().unwrap().len(), 1);
}
