[package]
name = "actix-restful-cli"
version.workspace = true
edition.workspace = true
default-run = "actix-restful"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt.workspace = true

[[bin]]
name = "actix-restful"
path = "src/main.rs"
