[package]
name = "actix-restful-cli"
version = "0.1.0"
edition = "2021"
default-run = "actix-restful"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"

[[bin]]
name = "actix-restful"
path = "src/main.rs"