CREATE TABLE IF NOT EXISTS model1 (
    id BIGSERIAL PRIMARY KEY,
    string TEXT NOT NULL,
    i32 INTEGER NOT NULL,
    i64 BIGINT NOT NULL,
    f64 DOUBLE PRECISION NOT NULL,
    bool BOOLEAN NOT NULL,
    opt_str TEXT,
    dt TIMESTAMPTZ NOT NULL,
    ndt TIMESTAMPTZ NOT NULL,
    ndt2 TIMESTAMP NOT NULL,
    nd DATE NOT NULL,
    nt TIME NOT NULL,
    vecu8 BYTEA NOT NULL,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);
